version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
  - package-ecosystem: gomod
    directory: /go/weave-wazero
    schedule:
      interval: monthly
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: /sidecars/webrtc
    schedule:
      interval: monthly
    labels:
      - dependencies
