[package]
name = "weave-transform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
wasmparser.workspace = true
wasm-encoder.workspace = true
weave-core.workspace = true

[dev-dependencies]
wat.workspace = true
wasmtime.workspace = true
