#!/usr/bin/env node
// Dependency-free, offline, deterministic single-file packaging. Libraries are
// embedded verbatim apart from static module-specifier rewrites; no fork/minify.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { resolvePiCompiler } from "./compiler.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const args = process.argv.slice(2);
const usage = "usage: node demos/pi-migration/build.mjs [--out-dir PATH] [--update-test-fixture]";
let output = path.join(here, "dist");
let updateTestFixture = false;
let selectedOutput = false;
for (let index = 0; index < args.length; index++) {
  if (args[index] === "--out-dir" && !selectedOutput) {
    const value = args[++index];
    if (!value || value.startsWith("--")) throw new Error(usage);
    output = path.resolve(value);
    selectedOutput = true;
  } else if (args[index] === "--update-test-fixture" && !updateTestFixture) {
    updateTestFixture = true;
  } else {
    throw new Error(usage);
  }
}
const compiler = resolvePiCompiler();
await mkdir(output, { recursive: true });
const wovenPath = path.join(output, "pi.woven.wasm");
const transformed = spawnSync(compiler.command, ["transform", path.join(here, "pi.wat"), "-o", wovenPath, "--period", "64", "--stack-pages", "2"], { cwd: root, stdio: "inherit", timeout: 30000 });
if (transformed.error || transformed.status !== 0) throw transformed.error || new Error("transform failed; build the weave CLI first (cargo build --release -p weave-cli)");
const wasm = await readFile(wovenPath);
if (!WebAssembly.validate(wasm)) throw new Error("Pi compiler output is not valid WebAssembly");
if (updateTestFixture) {
  const fixture = {
    sourceSha256: createHash("sha256").update(await readFile(path.join(here, "pi.wat"))).digest("hex"),
    wasmSha256: createHash("sha256").update(wasm).digest("hex"),
    period: 64,
    stackPages: 2,
    base64: wasm.toString("base64"),
  };
  const header = "// Generated by: node demos/pi-migration/build.mjs --update-test-fixture\n"
    + "// Source and binary hashes prevent JavaScript-only CI from using a stale guest.\n";
  await writeFile(path.join(here, "pi-fixture.mjs"), `${header}export const PI_FIXTURE = Object.freeze(${JSON.stringify(fixture, null, 2)});\n`);
}
const files = new Map([
  [path.join(root, "js/weave.mjs"), "weave-demo:core"],
  [path.join(root, "js/weave-browser.mjs"), "weave-demo:browser"],
  [path.join(root, "packages/browser-transports/src/index.mjs"), "weave-demo:transports"],
  [path.join(root, "packages/webrtc-session/src/index.mjs"), "weave-demo:session"],
  [path.join(here, "runtime.mjs"), "weave-demo:runtime"],
  [path.join(here, "rtc-diagnostics.mjs"), "weave-demo:rtc-diagnostics"],
  [path.join(here, "tab-stream.mjs"), "weave-demo:tab-stream"],
  [path.join(here, "tab-indicator.mjs"), "weave-demo:tab-indicator"],
  [path.join(here, "app.mjs"), "weave-demo:app"],
]);
const imports = {}, hashes = {};
for (const [filename, name] of files) {
  const original = await readFile(filename, "utf8");
  const source = original.replace(/(^\s*import\s+(?:[^;]*?\s+from\s*)?)(["'])([^"']+)\2/gm, (match, prefix, quote, specifier) => {
    const resolved = files.get(path.resolve(path.dirname(filename), specifier));
    if (!resolved) throw new Error(`Unbundled dependency ${specifier} in ${filename}`);
    return `${prefix}${quote}${resolved}${quote}`;
  });
  hashes[path.relative(root, filename)] = createHash("sha256").update(original).digest("hex");
  imports[name] = `data:text/javascript;base64,${Buffer.from(source).toString("base64")}`;
}
const escape = (text) => text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
const json = (value) => JSON.stringify(value).replaceAll("<", "\\u003c");
const workload = { base64: wasm.toString("base64"), sha256: createHash("sha256").update(wasm).digest("hex"), bytes: wasm.length, sources: hashes };
const template = await readFile(path.join(here, "index.template.html"), "utf8");
const css = await readFile(path.join(here, "style.css"), "utf8");
const license = await readFile(path.join(root, "LICENSE"), "utf8");
const html = template.replace("/*__STYLE__*/", () => css).replace("/*__WORKLOAD__*/", () => json(workload)).replace("/*__IMPORTMAP__*/", () => json({ imports })).replace("/*__LICENSE__*/", () => escape(license));
if (/\/\*__[A-Z]+__\*\//.test(html)) throw new Error("unreplaced template placeholder");
await writeFile(path.join(output, "index.html"), html);
await writeFile(path.join(output, "build-manifest.json"), JSON.stringify({ htmlSha256: createHash("sha256").update(html).digest("hex"), htmlBytes: Buffer.byteLength(html), ...workload, base64: undefined }, null, 2) + "\n");
console.log(`Single-file demo: ${path.join(output, "index.html")} (${Buffer.byteLength(html).toLocaleString()} bytes)`);
console.log(`Only index.html is needed for deployment. Wasm SHA-256: ${workload.sha256}`);
